(function(root){
  "use strict";
  var KeyboardUI = root.KeyboardUI = (root.KeyboardUI || {});

//maps variables to jQuery elements
  KeyboardUI.$keys = {
    $backTick: $("#backTick"),
    $one: $("#one"),
    $two: $("#two"),
    $three: $("#three"),
    $four: $("#four"),
    $five: $("#five"),
    $six: $("#six"),
    $seven: $("#seven"),
    $eight: $("#eight"),
    $nine: $("#nine"),
    $zero: $("#zero"),
    $minus: $("#minus"),
    $equals: $("#equals"),
    $backSpace: $("#backSpace"),
    //
    $q: $("#q"),
    $w: $("#w"),
    $e: $("#e"),
    $r: $("#r"),
    $t: $("#t"),
    $y: $("#y"),
    $u: $("#u"),
    $i: $("#i"),
    $o: $("#o"),
    $p: $("#p"),
    $openBracket: $("#openBracket"),
    $closeBracket: $("#closeBracket"),
    $backSlash: $("#backSlash"),
    //
    $a: $("#a"),
    $s: $("#s"),
    $d: $("#d"),
    $f: $("#f"),
    $g: $("#g"),
    $h: $("#h"),
    $j: $("#j"),
    $k: $("#k"),
    $l: $("#l"),
    $semicolon: $("#semicolon"),
    $apostrophe: $("#apostrophe"),
    $enter: $("#enter"),
    //
    $z: $("#z"),
    $x: $("#x"),
    $c: $("#c"),
    $v: $("#v"),
    $b: $("#b"),
    $n: $("#n"),
    $m: $("#m"),
    $comma: $("#comma"),
    $period: $("#period"),
    $slash: $("#slash"),
    //
    $space: $("#space"),
    $up: $("#up"),
    $left: $("#left"),
    $down: $("#down"),
    $right: $("#right"),
    $beat1: $("#beat1"),
    $beat2: $("#beat2"),
    $beat3: $("#beat3"),
    $beat4: $("#beat4"),
    $beat5: $("#beat5"),
    $beat6: $("#beat6"),
    $beat7: $("#beat7"),
    $beat8: $("#beat8")
  };
})(this);
